name: flutter_chess
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider:
  fluttericon: 
  day_night_switcher: 
  firebase_core: 
  firebase_auth: 
  firebase_database: 
  http: 
  shared_preferences: 
  flutter_svg: 
  flutter_styled_toast: 
  flutter_screenutil: 
  date_format: 
  percent_indicator: 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true



  assets:
    - assets/Images/background.svg
    - assets/Images/profile.jpg
