// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCviJv2WuN7TjUaM4we70cwuZon5WtIzv8',
    appId: '1:835262193978:web:bbe0f6beaa8bea11d43003',
    messagingSenderId: '835262193978',
    projectId: 'chess-d1226',
    authDomain: 'chess-d1226.firebaseapp.com',
    databaseURL: 'https://chess-d1226-default-rtdb.firebaseio.com',
    storageBucket: 'chess-d1226.appspot.com',
    measurementId: 'G-HZNERE60P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy-A0cU8dE7vWjKPvmzZmK-A23JZFjZSE',
    appId: '1:835262193978:android:2b3ce9fca28b4ebad43003',
    messagingSenderId: '835262193978',
    projectId: 'chess-d1226',
    databaseURL: 'https://chess-d1226-default-rtdb.firebaseio.com',
    storageBucket: 'chess-d1226.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChx1jGbxXNFsiUe1Cacc023osvi2sr398',
    appId: '1:835262193978:ios:e1e1fcd6225c009ed43003',
    messagingSenderId: '835262193978',
    projectId: 'chess-d1226',
    databaseURL: 'https://chess-d1226-default-rtdb.firebaseio.com',
    storageBucket: 'chess-d1226.appspot.com',
    iosClientId: '835262193978-ls3dkdu6n4ffb81c4pnfjo2noktjpd6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChx1jGbxXNFsiUe1Cacc023osvi2sr398',
    appId: '1:835262193978:ios:e1e1fcd6225c009ed43003',
    messagingSenderId: '835262193978',
    projectId: 'chess-d1226',
    databaseURL: 'https://chess-d1226-default-rtdb.firebaseio.com',
    storageBucket: 'chess-d1226.appspot.com',
    iosClientId: '835262193978-ls3dkdu6n4ffb81c4pnfjo2noktjpd6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalV3',
  );
}
